export const topPlayers = [
  "school phobia",
  "EMENES 1",
  "MAD AD",
  "Razørk Activoo",
  "Kite Machine",
  "good in head",
  "supaaaaaaaaaaaaa",
  "TwTv Kaos Angel",
  "zyb",
  "FaithXD",
  "MagiFelix5",
  "OAT MILK OTIS",
  "stevest4r",
  "RGE Malrang",
  "Built",
  "Kirei sama",
  "CaÞs",
  "RaiderGO",
  "Sertuss",
  "call of power",
  "Ràion",
  "Tempt0206",
  "Ttv Lathyrus",
  "Lathyrus",
  "Jumalan torni",
  "ViV SkewMond",
  "Skeanz",
  "X7 Chasy",
  "SPKTRA",
  "eIramir",
  "Kalista",
  "AØH",
  "zhypey",
  "Dzu",
  "Venour",
  "Drututt",
  "Yikeru",
  "Finn1",
  "sénécá",
  "RRubyLOL",
  "Vizícsacsi",
  "Mountain Wolf",
  "FUN k3y",
  "Maςaquiñø",
  "Zoelys03",
  "Jαvier",
  "EMDDD",
  "Mutant Grzegorz",
  "LOOCA",
  "sportsgrillTV",
  "Cutie Sexy Focus",
  "Peng Mid",
  "FFDP",
  "Pride0",
  "LDLC Exakick1",
  "FNC Upset03",
  "FEB1VEN",
  "cbt machine",
  "rivellablue",
  "breaking free",
  "Serendrip",
  "Frogmouth",
  "Cutie Sexy Jool",
  "Doss1",
  "Tanu2",
  "Engage",
  "Retnyam",
  "BABO SUP",
  "ragoshi UwU",
  "WO DIUUUUUUUUUU",
  "buff tοp",
  "HenryEtooMessi",
  "wuyu",
  "Iziio",
  "Regn",
  "Jesklaa",
  "mid npc",
  "SK Jezu",
  "PeberJack",
  "Neramin1",
  "Uzi Trainee",
  "VIking 105 kg",
  "shimawaru7",
  "SOY MILK SAM",
  "Tore den store",
  "HoIyPhoenîx",
  "Lekcycc",
  "Mid Lurk3r",
  "Mαster Oogwαy",
  "Veignorem",
  "TRYHARD NØ CHAT",
  "ACD",
  "Villager C",
  "Mr Tickle",
  "BSC Coldraa",
  "Cinkrof mid acc",
  "SHERNFlRE",
  "TwTv Lurkz77",
  "Overcoming",
  "gdgd top acc",
  "GanjaDragonlord"
];
